### ISSUE TITLE
Variables set in defaults-set.yml not used

### ISSUE THREAD

**Issue by jwerak** [csmart/ansible-role-virt-infra#69]
Variables `virt_infra_architecture` and `virt_infra_domainname` are checked and defined only in file _defaults-set.yml_. 

Is this used somewhere else later in pipeline, or can this file be safely removed?

**Comment by csmart** [comment]
Hi @jwerak, thanks for the posting an issue. You're right they're only used in `default-set.yml` I think because I was anticipating supporting running VMs of architectures on a host (for example, letting you emulate an ARM machine on an x86_64 machine). I'd be happy to remove these and just default the variable when needed, if we enable support in the future. Cheers!

**Comment by jwerak** [comment]
Hi, here is the PR: https://github.com/csmart/ansible-role-virt-infra/pull/70

**Comment by csmart** [comment]
Thanks! I've merged it in.
